version: '3.7'

networks:
  wordpress-net:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.1.0/24
          ip_range: 192.168.1.240/24

services:
  mysql-server-wordpress:
    image: mysql:8.0-oracle
    container_name: mysql-server-wordpress
    environment:
      MYSQL_DATABASE: "wordpress"
      MYSQL_USER: "wordpress"
      MYSQL_PASSWORD: "wordpress_pwd"
      MYSQL_ROOT_PASSWORD: "root_pwd"
    networks:
      wordpress-net:
        ipv4_address: 192.168.1.140
    command: >
      --character-set-server=utf8
      --collation-server=utf8_bin
      --default-authentication-plugin=mysql_native_password
    restart: unless-stopped

  wordpress:
    image: wordpress:latest
    container_name: wordpress
    networks:
      wordpress-net:
        ipv4_address: 192.168.1.141
    environment:
      WORDPRESS_DB_HOST: "mysql-server-wordpress"
      WORDPRESS_DB_USER: "wordpress"
      WORDPRESS_DB_PASSWORD: "wordpress_pwd"
      WORDPRESS_DB_NAME: "wordpress"
    ports:
      - "8090:80"
    restart: unless-stopped
